'use client'

import Link from 'next/link'
import { useMemo, useState } from 'react'
import {
  AlertCircle, ArrowLeft, ArrowRight, Building2, Calendar, Check, CheckCircle2, ChevronDown,
  Clock3, Download, FileText, Filter, IndianRupee, Mail, MapPin, MoreHorizontal,
  Paperclip, Phone, Plus, ReceiptText, RotateCcw, Search, ShieldCheck, SlidersHorizontal, Tags,
  Trash2, Upload, UserPlus, Users, WalletCards, X,
} from 'lucide-react'
import { AmountDisplay } from '@/components/shared/amount-display'
import { StatusBadge } from '@/components/shared/status-badge'

type ExpenseStatus = 'paid' | 'partial' | 'unpaid'
type Expense = { id: string; date: string; vendor: string; note: string; category: string; amount: number; paid: number; status: ExpenseStatus; owner: string }

const expenses: Expense[] = [
  { id: 'EXP-1048', date: '21 Aug 2026', vendor: 'Shree Balaji Cement', note: 'Cement · 120 bags', category: 'Civil', amount: 58200, paid: 0, status: 'unpaid', owner: 'Amit' },
  { id: 'EXP-1047', date: '20 Aug 2026', vendor: 'Mahalaxmi Steels', note: 'TMT steel delivery', category: 'Civil', amount: 146800, paid: 100000, status: 'partial', owner: 'Suhail' },
  { id: 'EXP-1046', date: '19 Aug 2026', vendor: 'Rakesh Electricals', note: 'Floor 4 conduit work', category: 'Admin', amount: 28400, paid: 28400, status: 'paid', owner: 'Priya' },
  { id: 'EXP-1045', date: '18 Aug 2026', vendor: 'Apex Print House', note: 'Site hoarding print', category: 'Marketing', amount: 12600, paid: 12600, status: 'paid', owner: 'Suhail' },
  { id: 'EXP-1044', date: '17 Aug 2026', vendor: 'Patel Transport', note: 'Material unloading', category: 'Others', amount: 8500, paid: 0, status: 'unpaid', owner: 'Amit' },
  { id: 'EXP-1043', date: '15 Aug 2026', vendor: 'Metro Ready Mix', note: 'M30 concrete · slab', category: 'Civil', amount: 224000, paid: 224000, status: 'paid', owner: 'Priya' },
]

const vendors = [
  { id: 'balaji', name: 'Shree Balaji Cement', category: 'Materials', phone: '+91 98201 44516', billed: 482600, paid: 370200, open: 112400, count: 12 },
  { id: 'mahalaxmi', name: 'Mahalaxmi Steels', category: 'Materials', phone: '+91 98921 10218', billed: 746800, paid: 600000, open: 146800, count: 8 },
  { id: 'rakesh', name: 'Rakesh Electricals', category: 'Contractor', phone: '+91 97682 24009', billed: 214500, paid: 214500, open: 0, count: 9 },
  { id: 'metro', name: 'Metro Ready Mix', category: 'Materials', phone: '+91 99870 65122', billed: 922000, paid: 922000, open: 0, count: 5 },
  { id: 'patel', name: 'Patel Transport', category: 'Logistics', phone: '+91 90041 33128', billed: 88500, paid: 64000, open: 24500, count: 11 },
]

function PageHeader({ eyebrow, title, description, actions }: { eyebrow: string; title: string; description: string; actions?: React.ReactNode }) {
  return <header className="product-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div>{actions && <div className="heading-actions">{actions}</div>}</header>
}

function SearchField({ value, onChange, placeholder }: { value: string; onChange: (value: string) => void; placeholder: string }) {
  return <label className="product-search"><Search size={16} /><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} />{value && <button aria-label="Clear search" onClick={() => onChange('')}><X size={14} /></button>}</label>
}

function EmptyState({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) {
  return <div className="empty-state"><span><Search size={22} /></span><h3>{title}</h3><p>{description}</p>{action}</div>
}

function FilterTabs({ value, onChange, values }: { value: string; onChange: (value: string) => void; values: string[] }) {
  return <div className="filter-tabs">{values.map((item) => <button className={value === item ? 'is-active' : ''} onClick={() => onChange(item)} key={item}>{item}</button>)}</div>
}

export function ExpensesScreen({ initialQuery = '' }: { initialQuery?: string }) {
  const [query, setQuery] = useState(initialQuery)
  const [status, setStatus] = useState('All')
  const filtered = useMemo(() => expenses.filter((expense) => (status === 'All' || expense.status === status.toLowerCase()) && `${expense.vendor} ${expense.note} ${expense.id}`.toLowerCase().includes(query.toLowerCase())), [query, status])
  return <div className="product-page">
    <PageHeader eyebrow="Ledger" title="Expenses" description="Review, filter and manage every cost recorded for this site." actions={<><button className="secondary-button" onClick={() => window.print()}><Download size={16}/> Export</button><Link className="primary-button" href="/expenses/new"><Plus size={17}/> Add expense</Link></>} />
    <section className="mini-stat-grid"><MiniStat label="August spend" value={<AmountDisplay amount={1268400} size="lg"/>} icon={<WalletCards size={18}/>} /><MiniStat label="Outstanding" value={<AmountDisplay amount={354200} size="lg"/>} icon={<Clock3 size={18}/>} /><MiniStat label="Entries" value="18" detail="5 added this week" icon={<ReceiptText size={18}/>} /></section>
    <section className="panel product-list-panel"><div className="list-toolbar"><SearchField value={query} onChange={setQuery} placeholder="Search vendor, description or ID"/><button className="secondary-button small"><Calendar size={15}/> Aug 1–31</button><button className="secondary-button small"><SlidersHorizontal size={15}/> More filters</button></div><FilterTabs value={status} onChange={setStatus} values={['All', 'Paid', 'Partial', 'Unpaid']} />
      {filtered.length ? <div className="product-table expense-list"><div className="product-table-head"><span>Expense</span><span>Category</span><span>Recorded by</span><span>Status</span><span>Amount</span><span/></div>{filtered.map((expense) => <Link className="product-row" href={`/expenses/${expense.id}`} key={expense.id}><span className="primary-cell"><i>{expense.vendor[0]}</i><span><strong>{expense.vendor}</strong><small>{expense.date} · {expense.note}</small></span></span><span>{expense.category}</span><span>{expense.owner}</span><span><StatusBadge status={expense.status}/></span><span className="amount-cell"><AmountDisplay amount={expense.amount} size="md"/><small>{expense.status === 'partial' && `₹${(expense.amount - expense.paid).toLocaleString('en-IN')} due`}</small></span><ArrowRight size={16}/></Link>)}</div> : <EmptyState title="No matching expenses" description="Try removing a filter or search for a different vendor." action={<button className="secondary-button" onClick={() => { setQuery(''); setStatus('All') }}>Clear filters</button>} />}
    </section>
  </div>
}

function MiniStat({ label, value, detail, icon }: { label: string; value: React.ReactNode; detail?: string; icon: React.ReactNode }) {
  return <article className="mini-stat"><span>{icon}</span><div><p>{label}</p><strong>{value}</strong>{detail && <small>{detail}</small>}</div></article>
}

export function ExpenseDetailScreen({ id }: { id: string }) {
  const [voidOpen, setVoidOpen] = useState(false)
  const expense = expenses.find((item) => item.id === id) ?? expenses[0]
  return <div className="product-page detail-page">
    <Link className="back-link" href="/expenses"><ArrowLeft size={15}/> All expenses</Link>
    <PageHeader eyebrow={expense.id} title={expense.vendor} description={`${expense.note} · Recorded by ${expense.owner}`} actions={<><button className="secondary-button"><Download size={16}/> Download</button><button className="secondary-button danger-text" onClick={() => setVoidOpen(true)}><Trash2 size={16}/> Void</button></>} />
    {voidOpen && <div className="inline-confirm danger"><AlertCircle size={20}/><div><strong>Void this expense?</strong><p>It will leave totals but remain in the audit log. A reason and action PIN will be required.</p></div><button className="secondary-button" onClick={() => setVoidOpen(false)}>Keep</button><button className="danger-button">Continue</button></div>}
    <section className="detail-grid"><div className="detail-main">
      <article className="panel detail-hero"><div><p>Total amount</p><AmountDisplay amount={expense.amount} size="xl" showHelper/></div><StatusBadge status={expense.status}/><div className="payment-progress"><span style={{width: `${Math.round(expense.paid / expense.amount * 100)}%`}}/></div><div className="detail-money-grid"><span><small>Paid</small><AmountDisplay amount={expense.paid} size="md"/></span><span><small>Outstanding</small><AmountDisplay amount={expense.amount - expense.paid} size="md"/></span><Link className="primary-button" href={`/expenses/${expense.id}/payment`}>Record payment</Link></div></article>
      <article className="panel detail-section"><div className="panel-heading"><div><h2>Payment history</h2><p>All money recorded against this expense</p></div></div>{expense.paid ? <div className="timeline"><div><i><Check size={14}/></i><span><strong>{expense.status === 'partial' ? 'Partial payment' : 'Paid in full'}</strong><small>20 Aug 2026 · Bank transfer · Suhail</small></span><AmountDisplay amount={expense.paid} size="md"/></div></div> : <EmptyState title="No payment recorded" description="This expense is currently fully outstanding."/>}</article>
      <article className="panel detail-section"><div className="panel-heading"><div><h2>Attachments</h2><p>Invoice, challan and supporting files</p></div><button className="secondary-button small"><Upload size={14}/> Upload</button></div><div className="file-card"><span><FileText size={19}/></span><div><strong>challan-1048.pdf</strong><small>PDF · 428 KB · Added by Amit</small></div><button className="icon-button"><Download size={16}/></button></div></article>
    </div><aside className="detail-aside"><article className="panel info-card"><h2>Expense details</h2><Info label="Date" value={expense.date}/><Info label="Category" value={expense.category}/><Info label="Vendor" value={expense.vendor}/><Info label="Recorded by" value={expense.owner}/><Info label="Site" value="Skyline Residency"/></article><article className="panel activity-card"><h2>Activity</h2><div><i/><span><strong>Expense created</strong><small>21 Aug, 10:42 AM · Amit</small></span></div><div><i/><span><strong>Challan attached</strong><small>21 Aug, 10:43 AM · Amit</small></span></div></article></aside></section>
  </div>
}

function Info({ label, value }: { label: string; value: string }) { return <div className="info-row"><span>{label}</span><strong>{value}</strong></div> }

export function VendorsScreen() {
  const [query, setQuery] = useState('')
  const filtered = vendors.filter((vendor) => vendor.name.toLowerCase().includes(query.toLowerCase()))
  return <div className="product-page"><PageHeader eyebrow="Directory" title="Vendors" description="See every supplier, contractor and their payment position." actions={<button className="primary-button"><Plus size={17}/> Add vendor</button>} /><section className="mini-stat-grid"><MiniStat label="Active vendors" value="24" detail="5 with open balances" icon={<Building2 size={18}/>} /><MiniStat label="Total billed" value={<AmountDisplay amount={2454400} size="lg"/>} icon={<ReceiptText size={18}/>} /><MiniStat label="Vendor outstanding" value={<AmountDisplay amount={283700} size="lg"/>} icon={<Clock3 size={18}/>} /></section><section className="panel product-list-panel"><div className="list-toolbar"><SearchField value={query} onChange={setQuery} placeholder="Search vendors"/><button className="secondary-button small"><Filter size={15}/> Category</button></div>{filtered.length ? <div className="vendor-grid">{filtered.map((vendor) => <Link href={`/vendors/${vendor.id}`} className="vendor-card" key={vendor.id}><div className="vendor-card-top"><i>{vendor.name[0]}</i><span className={`balance-dot ${vendor.open ? 'has-open' : ''}`}>{vendor.open ? 'Open balance' : 'Clear'}</span></div><h3>{vendor.name}</h3><p>{vendor.category} · {vendor.count} expenses</p><div><span><small>Total billed</small><AmountDisplay amount={vendor.billed} size="md"/></span><span><small>Outstanding</small><AmountDisplay amount={vendor.open} size="md"/></span></div><footer>{vendor.phone}<ArrowRight size={15}/></footer></Link>)}</div> : <EmptyState title="No vendors found" description="Try another name or clear your search." action={<button className="secondary-button" onClick={() => setQuery('')}>Clear search</button>}/>}</section></div>
}

export function VendorDetailScreen({ id }: { id: string }) {
  const vendor = vendors.find((item) => item.id === id) ?? vendors[0]
  const vendorExpenses = expenses.filter((item) => item.vendor === vendor.name || item.category === 'Civil').slice(0, 4)
  return <div className="product-page detail-page"><Link className="back-link" href="/vendors"><ArrowLeft size={15}/> All vendors</Link><PageHeader eyebrow={vendor.category} title={vendor.name} description={`${vendor.count} expenses · Vendor since January 2026`} actions={<><button className="secondary-button">Edit vendor</button><Link className="primary-button" href="/expenses/new"><Plus size={17}/> New expense</Link></>} /><section className="mini-stat-grid"><MiniStat label="Total billed" value={<AmountDisplay amount={vendor.billed} size="lg"/>} icon={<ReceiptText size={18}/>} /><MiniStat label="Total paid" value={<AmountDisplay amount={vendor.paid} size="lg"/>} icon={<CheckCircle2 size={18}/>} /><MiniStat label="Outstanding" value={<AmountDisplay amount={vendor.open} size="lg"/>} icon={<Clock3 size={18}/>} /></section><section className="detail-grid"><article className="panel product-list-panel detail-main"><div className="panel-heading"><div><h2>Expense history</h2><p>All transactions with this vendor</p></div><button className="secondary-button small"><Download size={14}/> Statement</button></div><div className="compact-list">{vendorExpenses.map((expense) => <Link href={`/expenses/${expense.id}`} key={expense.id}><span><strong>{expense.note}</strong><small>{expense.date} · {expense.id}</small></span><StatusBadge status={expense.status}/><AmountDisplay amount={expense.amount} size="md"/><ArrowRight size={15}/></Link>)}</div></article><aside className="detail-aside"><article className="panel info-card"><h2>Contact details</h2><Info label="Phone" value={vendor.phone}/><Info label="GSTIN" value="27AAHCS8831Q1Z6"/><Info label="Category" value={vendor.category}/><Info label="Site" value="Skyline Residency"/></article><article className="panel note-card"><h2>Internal note</h2><p>Preferred morning delivery. Confirm unloading labour one day in advance.</p></article></aside></section></div>
}

export function PaymentsScreen() {
  const [tab, setTab] = useState('All payments')
  return <div className="product-page"><PageHeader eyebrow="Cash movement" title="Payments" description="Track payments, part-payments and who paid on behalf of the site." actions={<button className="secondary-button" onClick={() => window.print()}><Download size={16}/> Export</button>} /><section className="mini-stat-grid"><MiniStat label="Paid this month" value={<AmountDisplay amount={914200} size="lg"/>} icon={<CheckCircle2 size={18}/>} /><MiniStat label="Cash payments" value={<AmountDisplay amount={184000} size="lg"/>} icon={<IndianRupee size={18}/>} /><MiniStat label="Personal advances" value={<AmountDisplay amount={96500} size="lg"/>} icon={<Users size={18}/>} /></section><section className="panel product-list-panel"><FilterTabs value={tab} onChange={setTab} values={['All payments', 'Cash', 'Bank transfer', 'Cheque']} /><div className="payment-list">{expenses.filter((item) => item.paid > 0).map((expense) => <Link href={`/expenses/${expense.id}`} key={expense.id}><i><Check size={15}/></i><span><strong>{expense.vendor}</strong><small>{expense.date} · {tab === 'All payments' ? 'Bank transfer' : tab} · Paid by {expense.owner}</small></span><span><small>Against {expense.id}</small><AmountDisplay amount={expense.paid} size="md"/></span><ArrowRight size={16}/></Link>)}</div></section></div>
}

export function CategoriesScreen() {
  const [adding, setAdding] = useState(false)
  const groups = [{name:'Civil', tone:'amber', total:'₹8.6L', items:['Cement & concrete','Steel & reinforcement','Labour contractor','Electrical works']},{name:'Admin', tone:'charcoal', total:'₹2.4L', items:['Site office','Travel & fuel','Legal & approvals']},{name:'Marketing', tone:'sand', total:'₹1.1L', items:['Print & signage','Digital campaigns']},{name:'Others', tone:'pale', total:'₹52K', items:['Uncategorised']}]
  return <div className="product-page"><PageHeader eyebrow="Configuration" title="Categories" description="Keep expense classification consistent across the whole team." actions={<button className="primary-button" onClick={() => setAdding(true)}><Plus size={17}/> Add subcategory</button>} />{adding && <div className="inline-create"><label><span>New subcategory</span><input autoFocus placeholder="e.g. Plumbing works"/></label><label><span>Under category</span><button>Civil <ChevronDown size={15}/></button></label><button className="secondary-button" onClick={() => setAdding(false)}>Cancel</button><button className="primary-button" onClick={() => setAdding(false)}>Add</button></div>}<div className="category-admin-grid">{groups.map((group) => <article className="panel category-admin" key={group.name}><header><i className={group.tone}/><div><h2>{group.name}</h2><p>{group.items.length} subcategories</p></div><strong>{group.total}</strong><button className="icon-button"><MoreHorizontal size={17}/></button></header><div>{group.items.map((item) => <button key={item}><span>{item}</span><em>Active</em><MoreHorizontal size={16}/></button>)}</div><footer><button onClick={() => setAdding(true)}><Plus size={14}/> Add subcategory</button></footer></article>)}</div></div>
}

export function TeamScreen() {
  const [invite, setInvite] = useState(false)
  const people = [{initials:'SK',name:'Suhail Khan',email:'suhail@gokulesh.in',role:'Owner',activity:'Now'},{initials:'PA',name:'Priya Agarwal',email:'priya@gokulesh.in',role:'Admin',activity:'12 min ago'},{initials:'AM',name:'Amit Mehta',email:'amit@gokulesh.in',role:'Member',activity:'1 hr ago'},{initials:'RJ',name:'Rohan Jain',email:'rohan@gokulesh.in',role:'Viewer',activity:'Yesterday'}]
  return <div className="product-page"><PageHeader eyebrow="Access" title="Team" description="Manage who can view, record and approve site expenses." actions={<button className="primary-button" onClick={() => setInvite(true)}><UserPlus size={17}/> Invite member</button>} />{invite && <div className="inline-create invite-form"><label><span>Email or phone</span><input autoFocus placeholder="name@gokulesh.in"/></label><label><span>Role</span><button>Member <ChevronDown size={15}/></button></label><button className="secondary-button" onClick={() => setInvite(false)}>Cancel</button><button className="primary-button" onClick={() => setInvite(false)}>Send invite</button></div>}<section className="panel product-list-panel"><div className="team-table"><div className="team-head"><span>Member</span><span>Role</span><span>Last active</span><span>Status</span><span/></div>{people.map((person) => <div className="team-row" key={person.email}><span className="primary-cell"><i>{person.initials}</i><span><strong>{person.name}</strong><small>{person.email}</small></span></span><span><button className="role-select">{person.role}<ChevronDown size={13}/></button></span><span>{person.activity}</span><span className="member-status"><i/> Active</span><button className="icon-button"><MoreHorizontal size={17}/></button></div>)}</div></section><section className="permission-panel panel"><div><ShieldCheck size={21}/><span><h2>Role permissions</h2><p>Owners manage everything. Admins manage expenses and payments. Members can record entries. Viewers are read-only.</p></span></div><button className="secondary-button">View permission matrix</button></section></div>
}

export function AuditScreen() {
  const activity = [{icon:<Plus/>,action:'Expense created',detail:'Amit added EXP-1048 for Shree Balaji Cement',time:'Today, 10:42 AM',type:'Expense'},{icon:<Upload/>,action:'Attachment uploaded',detail:'Amit added challan-1048.pdf',time:'Today, 10:43 AM',type:'File'},{icon:<Check/>,action:'Payment recorded',detail:'Suhail recorded ₹1,00,000 against EXP-1047',time:'Yesterday, 4:18 PM',type:'Payment'},{icon:<RotateCcw/>,action:'Expense updated',detail:'Priya changed category from Others to Civil',time:'Yesterday, 1:05 PM',type:'Change'},{icon:<Users/>,action:'Member invited',detail:'Suhail invited Rohan Jain as Viewer',time:'18 Aug, 11:20 AM',type:'Access'}]
  return <div className="product-page"><PageHeader eyebrow="Compliance" title="Audit log" description="An append-only record of every important action across the site." actions={<button className="secondary-button"><Download size={16}/> Export log</button>} /><section className="panel product-list-panel"><div className="list-toolbar"><SearchField value="" onChange={() => {}} placeholder="Search actions or people"/><button className="secondary-button small"><Calendar size={15}/> Last 30 days</button><button className="secondary-button small"><Filter size={15}/> Action type</button></div><div className="audit-list">{activity.map((item, index) => <div key={index}><i>{item.icon}</i><span><strong>{item.action}</strong><small>{item.detail}</small></span><em>{item.type}</em><time>{item.time}</time><button className="icon-button"><ChevronDown size={16}/></button></div>)}</div><div className="audit-note"><ShieldCheck size={16}/> Audit records cannot be edited or deleted.</div></section></div>
}

export function SettingsScreen() {
  const [saved, setSaved] = useState(false)
  return <div className="product-page settings-page"><PageHeader eyebrow="Preferences" title="Settings" description="Configure the current site and your workspace preferences." /><div className="settings-layout"><nav><a className="is-active" href="#site">Site profile</a><a href="#notifications">Notifications</a><a href="#security">Security</a><a href="#exports">Exports</a><a href="#danger">Danger zone</a></nav><div className="settings-content"><section className="panel settings-section" id="site"><div><h2>Site profile</h2><p>Information shown across reports and exports.</p></div><div className="settings-fields"><label><span>Site name</span><input defaultValue="Skyline Residency"/></label><label><span>Project code</span><input defaultValue="SKY-MUM-26"/></label><label className="wide"><span>Site address</span><input defaultValue="Andheri East, Mumbai, Maharashtra"/></label></div></section><section className="panel settings-section" id="notifications"><div><h2>Notifications</h2><p>Choose which activity should reach you.</p></div><ToggleRow title="Payment due reminders" description="Get notified three days before an unpaid challan is due." initial/><ToggleRow title="New expense alerts" description="Notify me whenever a member records an expense." initial/><ToggleRow title="Weekly summary" description="Receive a Monday morning summary by email." initial={false}/></section><section className="panel settings-section" id="security"><div><h2>Action PIN</h2><p>Required before recording sensitive payment or void actions.</p></div><div className="security-box"><ShieldCheck size={20}/><span><strong>6-digit PIN is active</strong><small>Last changed 42 days ago</small></span><button className="secondary-button">Change PIN</button></div></section><section className="panel settings-section danger-zone" id="danger"><div><h2>Archive site</h2><p>Hide this site from everyday use while preserving its complete records.</p></div><button className="secondary-button danger-text">Archive Skyline Residency</button></section><div className="settings-save"><span>{saved && <><CheckCircle2 size={15}/> Changes saved</>}</span><button className="primary-button" onClick={() => {setSaved(true); setTimeout(() => setSaved(false), 1800)}}>Save changes</button></div></div></div></div>
}

function ToggleRow({ title, description, initial = false }: { title: string; description: string; initial?: boolean }) { const [on, setOn] = useState(initial); return <div className="toggle-row"><span><strong>{title}</strong><small>{description}</small></span><button className={`toggle ${on ? 'is-on' : ''}`} role="switch" aria-checked={on} onClick={() => setOn(!on)}><i/></button></div> }

export function RecordPaymentScreen({ id }: { id: string }) {
  const [mode, setMode] = useState('Bank transfer')
  const [saved, setSaved] = useState(false)
  return <div className="crud-page"><div className="crud-page-header"><Link className="icon-button" href={`/expenses/${id}`}><ArrowLeft size={20}/></Link><div><p className="eyebrow">{id}</p><h1>Record a payment</h1><p>Apply a payment against Mahalaxmi Steels.</p></div><Link className="icon-button close-button" href={`/expenses/${id}`}><X size={21}/></Link></div><div className="crud-workspace"><section className="form-card payment-context"><div><span>Expense total</span><AmountDisplay amount={146800} size="md"/></div><div><span>Already paid</span><AmountDisplay amount={100000} size="md"/></div><div><span>Outstanding</span><AmountDisplay amount={46800} size="lg"/></div></section><section className="form-card"><div className="form-section-heading"><span>01</span><div><h2>Payment details</h2><p>Record the amount and how it was paid.</p></div></div><div className="form-grid"><label className="field amount-field"><span>Amount paid</span><div className="input-with-icon"><IndianRupee size={21}/><input defaultValue="46,800"/></div><small>Maximum outstanding: ₹46,800</small></label><label className="field"><span>Payment date</span><div className="input-with-icon"><Calendar size={17}/><input defaultValue="21 Aug 2026"/></div></label><div className="field field-wide"><span>Payment mode</span><div className="payment-mode-grid">{['Cash','Bank transfer','Cheque','Voucher'].map((item) => <button className={mode === item ? 'is-active' : ''} onClick={() => setMode(item)} key={item}>{mode === item && <Check size={14}/>} {item}</button>)}</div></div><label className="field"><span>Paid by</span><div className="select-like"><span>Suhail Khan</span><ChevronDown size={16}/></div></label><label className="field"><span>Reference <em>Optional</em></span><input placeholder="UTR, cheque or voucher no."/></label><label className="field field-wide"><span>Remark <em>Optional</em></span><input placeholder="Add a note about this payment"/></label></div></section><section className="form-card"><div className="form-section-heading"><span>02</span><div><h2>Proof of payment</h2><p>Add an invoice, receipt or cheque image.</p></div></div><label className="upload-area"><Paperclip size={20}/><span><strong>Choose a receipt from your device</strong><small>PDF, JPG or PNG · Up to 10 MB</small></span><input type="file"/></label></section></div><div className="crud-footer"><p>{saved ? 'Payment recorded successfully.' : 'This action will update the expense balance.'}</p><div><Link className="secondary-button" href={`/expenses/${id}`}>Cancel</Link><button className="primary-button" disabled={saved} onClick={() => setSaved(true)}>{saved ? <Check size={17}/> : <ShieldCheck size={17}/>} {saved ? 'Payment recorded' : 'Verify PIN & record'}</button></div></div></div>
}
